# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a36138a92b27b36fc023f619801d6814840264087286f2930d622b66513659e6d6f1644e4962b55bb4640e82979dd872bfad3b3b9dc47c94872bd18964a0f3e

test:
  secret_key_base: 2655a5e4e191b980f8d6ddae75c32866181940021ddce5494b70deefa44ad6780c5dcb17e49a7e7675fb17222525e94eaf88bf22d34898e1928cb870b39c5974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
